<html><body><div><div itemprop="articleBody"><p>I was writing a RestructuredText document with bunch of code. Having the document doctested seemed like a good idea.</p><p><a class="reference external" href="https://testrun.org/tox/">Tox</a> and <a class="reference external" href="http://pytest.org/">pytest</a> were the natural choices here as I don't have to futz around with bootstrapping and testing scripts.</p><p>So I make this <tt class="docutils literal">tox.ini</tt> configuration:</p><div class="highlight"><pre><span/><span class="k">[tox]</span>
<span class="na">envlist</span> <span class="o">=</span> <span class="s">py34</span>

<span class="c1"># because I only have bunch of documents for now ...</span>
<span class="na">skipsdist</span> <span class="o">=</span> <span class="s">true</span>

<span class="k">[testenv]</span>
<span class="na">deps</span> <span class="o">=</span><span class="s"/>
<span class="s">    pytest</span>
<span class="s">    process-tests</span>
<span class="s">    mock</span>
<span class="s">    tornado</span>
<span class="s">    aspectlib</span>
<span class="na">commands</span> <span class="o">=</span> <span class="s">{posargs:py.test -vv}</span>
<span class="k">[pytest]</span>
<span class="na">norecursedirs</span> <span class="o">=</span><span class="s"/>
<span class="s">    .git</span>
<span class="s">    .tox</span>
<span class="na">addopts</span> <span class="o">=</span><span class="s"/>
<span class="s">    -rxEfs</span>
<span class="s">    --strict</span>
<span class="s">    --doctest-modules</span>
<span class="s">    --doctest-glob *.rst</span>
<span class="s">    --tb short</span>
</pre></div><p>So I was using Python 3.4 because I want to include some <tt class="docutils literal">asyncio</tt> examples. Unfortunately horror followed:</p><pre class="literal-block">
py34 runtests: PYTHONHASHSEED='2663730781'
py34 runtests: commands[0] | py.test -vv
============================= test session starts =============================
platform win32 -- Python 3.4.0 -- py-1.4.20 -- pytest-2.5.2 -- C:\docs\.tox\py34\Scripts\python.exe
collected 1 items

document.rst: [doctest] document.rst ERROR: InvocationError: 'C:\\docs\\.tox\\py34\\Scripts\\py.test.EXE -vv'
________________________________________________________________________________________________________ summary _________________________________________________________________
ERROR:   py34: commands failed
</pre><p>Now at this point I'm wondering what the hell is going on. Silent failure? Trying to run <tt class="docutils literal">py.test</tt> manually:</p><pre class="literal-block">
C:\docs&gt;.tox\py34\Scripts\py.test -vv
============================= test session starts =============================
platform win32 -- Python 3.4.0 -- py-1.4.20 -- pytest-2.5.2 -- C:\docs\.tox\py34\Scripts\python.exe
collected 1 items

document.rst: [doctest] document.rst
</pre><p>Gah!</p><p>Now at this point I remember that <tt class="docutils literal">py.test</tt> captures output by default. Could that cause problems? Seems so:</p><pre class="literal-block">
C:\docs&gt;.tox\py34\Scripts\py.test -vv --capture no
============================= test session starts =============================
platform win32 -- Python 3.4.0 -- py-1.4.20 -- pytest-2.5.2 -- C:\docs\.tox\py34\Scripts\python.exe
collected 1 items

document.rst: [doctest] document.rst
INTERNALERROR&gt; Traceback (most recent call last):
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\main.py", line 81, in wrap_session
INTERNALERROR&gt;     doit(config, session)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\main.py", line 118, in _main
INTERNALERROR&gt;     config.hook.pytest_runtestloop(session=session)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 377, in __call__
INTERNALERROR&gt;     return self._docall(methods, kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 388, in _docall
INTERNALERROR&gt;     res = mc.execute()
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 289, in execute
INTERNALERROR&gt;     res = method(**kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\main.py", line 138, in pytest_runtestloop
INTERNALERROR&gt;     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 377, in __call__
INTERNALERROR&gt;     return self._docall(methods, kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 388, in _docall
INTERNALERROR&gt;     res = mc.execute()
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 289, in execute
INTERNALERROR&gt;     res = method(**kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\runner.py", line 64, in pytest_runtest_protocol
INTERNALERROR&gt;     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\runner.py", line 74, in runtestprotocol
INTERNALERROR&gt;     reports.append(call_and_report(item, "call", log))
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\runner.py", line 110, in call_and_report
INTERNALERROR&gt;     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\main.py", line 162, in call_matching_hooks
INTERNALERROR&gt;     return hookmethod.pcall(plugins, **kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 381, in pcall
INTERNALERROR&gt;     return self._docall(methods, kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 388, in _docall
INTERNALERROR&gt;     res = mc.execute()
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 289, in execute
INTERNALERROR&gt;     res = method(**kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\capture.py", line 246, in pytest_runtest_makereport
INTERNALERROR&gt;     rep = __multicall__.execute()
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\core.py", line 289, in execute
INTERNALERROR&gt;     res = method(**kwargs)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\runner.py", line 208, in pytest_runtest_makereport
INTERNALERROR&gt;     longrepr = item.repr_failure(excinfo)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\_pytest\doctest.py", line 61, in repr_failure
INTERNALERROR&gt;     filelines = py.path.local(filename).readlines(cr=0)
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\py\_path\common.py", line 134, in readlines
INTERNALERROR&gt;     content = self.read('rU')
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\site-packages\py\_path\common.py", line 126, in read
INTERNALERROR&gt;     return f.read()
INTERNALERROR&gt;   File "C:\docs\.tox\py34\lib\encodings\cp1250.py", line 23, in decode
INTERNALERROR&gt;     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
INTERNALERROR&gt; UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 309: character maps to &lt;undefined&gt;

==============================  in 0.20 seconds ===============================
</pre><p>It would appear I had some non-ascii characters in there. It's as unavoidable as my own surname (Mărieș - with a ș, <strong>not ş</strong>) - the document is in Română (Romanian). But <tt class="docutils literal">cp1250</tt>?! My document is in <tt class="docutils literal"><span class="pre">utf-8</span></tt> - what's going on here?</p><p>Turns out Python 3 will use <a class="reference external" href="http://msdn.microsoft.com/en-us/library/windows/desktop/dd318070%28v=vs.85%29.aspx">GetACP</a> to get the <a class="reference external" href="https://docs.python.org/3/library/locale.html#locale.getpreferredencoding">preferred encoding</a> - which never seems to be the <tt class="docutils literal"><span class="pre">utf-8</span></tt> code page (<a class="reference external" href="http://en.wikipedia.org/wiki/Code_page_65001">cp65001</a>).</p><p>At this point I'm very intrigued and want to know if I could change that <cite>preferred encoding</cite>. But I can't:</p><pre class="literal-block">
C:\docs&gt;py -3 -c "import locale; print(locale.setlocale(locale.LC_ALL, 'eng_US.65001'))"
Traceback (most recent call last):
  File "&lt;string&gt;", line 1, in &lt;module&gt;
  File "C:\Python34\lib\locale.py", line 592, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
</pre><p>Was the argument format incorrect? I think not. With <tt class="docutils literal">cp1252</tt> it works fine:</p><pre class="literal-block">
C:\docs&gt;py -3 -c "import locale; print(locale.setlocale(locale.LC_ALL, 'eng_US.1252'))"
English_United States.1252
</pre><p>I just give up and just <a class="reference external" href="http://python-aspectlib.readthedocs.org/en/latest/introduction.html#the-weaver">monkey patch</a> that <tt class="docutils literal">open</tt> builtin. Because I still want <a class="reference external" href="http://pytest.org/">pytest</a>'s test discovery and I don't want to write a script reading up all the documents myself. I should make a <a class="reference external" href="http://pytest.org/">pytest</a> bug report at least ...</p><p>Made a <tt class="docutils literal">conftest.py</tt> and threw this in:</p><div class="note"><p class="first admonition-title">Note</p><p class="last">You think this is ugly? Try patching a builtin yourself.</p></div><div class="highlight"><pre><span/><span class="kn">import</span> <span class="nn">aspectlib</span>
<span class="n">aspectlib</span><span class="o">.</span><span class="n">weave</span><span class="p">(</span>
    <span class="nb">open</span><span class="p">,</span>
    <span class="k">lambda</span> <span class="nb">open</span><span class="p">:</span>
        <span class="k">lambda</span> <span class="n">name</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="s1">'r'</span><span class="p">,</span> <span class="o">*</span><span class="n">args</span><span class="p">,</span> <span class="n">encoding</span><span class="o">=</span><span class="s1">'utf8'</span><span class="p">,</span> <span class="o">**</span><span class="n">kwargs</span><span class="p">:</span>
            <span class="nb">open</span><span class="p">(</span><span class="n">name</span><span class="p">,</span> <span class="n">mode</span><span class="p">,</span> <span class="o">*</span><span class="n">args</span><span class="p">,</span> <span class="o">**</span><span class="n">kwargs</span><span class="p">)</span>
            <span class="k">if</span> <span class="s1">'b'</span> <span class="ow">in</span> <span class="n">mode</span> <span class="k">else</span>
            <span class="nb">open</span><span class="p">(</span><span class="n">name</span><span class="p">,</span> <span class="n">mode</span><span class="p">,</span> <span class="o">*</span><span class="n">args</span><span class="p">,</span> <span class="n">encoding</span><span class="o">=</span><span class="n">encoding</span><span class="p">,</span> <span class="o">**</span><span class="n">kwargs</span><span class="p">)</span>
<span class="p">)</span>
</pre></div><p>You can argue that's like killing mosquitoes with a bazooka, but I can get back to my doctests:</p><pre class="literal-block">
py34 runtests: PYTHONHASHSEED='1866354792'
py34 runtests: commands[0] | py.test -vv
============================= test session starts =============================
platform win32 -- Python 3.4.0 -- py-1.4.20 -- pytest-2.5.2 -- C:\docs\.tox\py34\Scripts\python.exe
collected 1 items

document.rst: [doctest] document.rst FAILED

================================== FAILURES ===================================
__________________________ [doctest] document.rst ___________________________
001 Silly stuff::
002
003     &gt;&gt;&gt; print(1)
Expected:
    2
Got:
    1

C:\docs\document.rst:3: DocTestFailure
=========================== short test summary info ===========================
FAIL document.rst
========================== 1 failed in 0.08 seconds ===========================
ERROR: InvocationError: 'C:\\docs\\.tox\\py34\\Scripts\\py.test.EXE -vv'
________________________________________________________________________________________________________ summary _____________________________
ERROR:   py34: commands failed
</pre><p>Yay!</p><p>Now before making a patch for these two problems in <a class="reference external" href="http://pytest.org/">pytest</a> I wonder if Python 3 should have an <cite>escape hatch</cite> - let users set the <cite>preferred encoding</cite> (via a fictive <tt class="docutils literal">PYTHONPREFERREDENCODING</tt> environment variable). At least on Windows where changing the system's locale is just hopeless. Because not all the applications and tools will get support for choosing encodings overnight. What do you think?</p></div></div></body></html>