<html><body><div><article>
	<h2 class="title">No Naked Excepts</h2> 
	<small>03 November 2013</small> 
 
	<p>You probably shouldn’t be using <code class="highlighter-rouge">except:</code> or <code class="highlighter-rouge">except Exception:</code> in
Python, sometimes called ‘catch-all exceptions’ or ‘naked excepts’.</p>

<p>I’ve tried to find a good article or blog post discussing this, but I
haven’t found any thorough discussions of the problems that arise.</p>

<p>Let’s take a look at exceptions. Python is excellent at throwing
exceptions, and errs on the side of more exceptions rather than
less. For example, this code will raise <code class="highlighter-rouge">KeyError</code>:</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="n">d</span> <span class="o">=</span> <span class="p">{</span><span class="s">'foobar'</span><span class="p">:</span> <span class="s">'Hello world'</span><span class="p">}</span>
<span class="k">print</span> <span class="n">d</span><span class="p">[</span><span class="s">'fooba'</span><span class="p">]</span> <span class="c"># spelling mistake!</span></code></pre></figure>

<p>The equivalent code in other languages will just return a sentinel
value. For example, JavaScript:</p>

<figure class="highlight"><pre><code class="language-javascript" data-lang="javascript"><span class="kd">var</span> <span class="nx">d</span> <span class="o">=</span> <span class="p">{</span><span class="s1">'foobar'</span><span class="p">:</span> <span class="s1">'Hello world'</span><span class="p">};</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">d</span><span class="p">[</span><span class="s1">'fooba'</span><span class="p">]);</span> <span class="c1">// prints 'undefined'</span></code></pre></figure>

<p>The main disadvantage of the JavaScript approach is that it’s easy to
get confused when you have your sentinel value in the hashmap. It’s
hard to distinguish <code class="highlighter-rouge"><span class="p">{}</span></code> from <code class="highlighter-rouge"><span class="p">{</span><span class="err">'foobar':</span><span class="w"> </span><span class="err">undefined</span><span class="p">}</span></code>.</p>

<p>So, there are a large number of situations that will throw exceptions
in Python.</p>

<p>Let’s consider the following piece of Django code, which fetches a
page, if it exists.</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">page</span> <span class="o">=</span> <span class="n">Page</span><span class="o">.</span><span class="n">objects</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s">"home"</span><span class="p">)</span>
<span class="k">except</span> <span class="n">Page</span><span class="o">.</span><span class="n">DoesNotExist</span><span class="p">:</span>
    <span class="n">page</span> <span class="o">=</span> <span class="bp">None</span></code></pre></figure>

<p>This works as expected. However, can you see the mistake in this
version?</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">page</span> <span class="o">=</span> <span class="n">Page</span><span class="o">.</span><span class="nb">object</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s">"home"</span><span class="p">)</span>
<span class="k">except</span><span class="p">:</span>
    <span class="n">page</span> <span class="o">=</span> <span class="bp">None</span></code></pre></figure>

<p>This code will actually throw <code class="highlighter-rouge">AttributeError</code>, since <code class="highlighter-rouge">Page.object</code>
doesn’t exist. However, since we used a catch-all <code class="highlighter-rouge">except</code>, we don’t
get any error. Subtle bugs like these can be a pain to track down
later.</p>

<p>The solution is to always name the specific exception you’re
expecting. Note there’s a nasty gotcha with catching multiple
exceptions:</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">do_something</span><span class="p">()</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">,</span> <span class="n">OtherException</span><span class="p">:</span>
    <span class="c"># This only catches SomeException and binds it to</span>
    <span class="c"># the variable OtherException</span>
    <span class="k">pass</span></code></pre></figure>

<p>The correct way to write this is:</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">do_something</span><span class="p">()</span>
<span class="k">except</span> <span class="p">(</span><span class="n">SomeException</span><span class="p">,</span> <span class="n">OtherException</span><span class="p">):</span>
    <span class="c"># the tuple ensures we catch both exceptions</span>
    <span class="k">pass</span></code></pre></figure>

<p>To avoid this gotcha completely, you can either use the excellent
<a href="https://pypi.python.org/pypi/pyflakes">Pyflakes</a> to check your code,
or use the <code class="highlighter-rouge">as</code> syntax:</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">do_something</span><span class="p">()</span>
<span class="k">except</span> <span class="p">(</span><span class="n">SomeException</span><span class="p">,</span> <span class="n">OtherException</span><span class="p">)</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="c"># not using a tuple here is a syntax error</span>
    <span class="k">pass</span></code></pre></figure>

<p>As with every rule, there are a few exceptions. The first is when
you’re allowing exceptions to propagate.</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">try</span><span class="p">:</span>
    <span class="n">some_resource</span> <span class="o">=</span> <span class="n">open_resource</span><span class="p">()</span>
    <span class="n">process_resource</span><span class="p">(</span><span class="n">some_resource</span><span class="p">)</span>
<span class="k">except</span><span class="p">:</span>
    <span class="c"># cleanup resource before propagating exception</span>
    <span class="n">some_resource</span><span class="o">.</span><span class="n">close</span><span class="p">()</span>
    <span class="c"># re-raise the original exception</span>
    <span class="k">raise</span></code></pre></figure>

<p>The other case is long running process, such as daemons:</p>

<figure class="highlight"><pre><code class="language-python" data-lang="python"><span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">do_daemon_stuff</span><span class="p">()</span>
    <span class="k">except</span><span class="p">:</span>
        <span class="n">log_exception_somewhere</span><span class="p">()</span></code></pre></figure>

<p>In this case, you only want a naked except at the very top level of
your program, and you want the exception to go somewhere. I like to
log to <a href="https://getsentry.com/">Sentry</a> or to a log file monitored by
<a href="https://papertrailapp.com/">Papertrail</a>.</p>

<p>To sum up: Only catch the exceptions you’re expecting to see. For all
other exceptions, you want to be informed about it so you can fix it.</p>

</article>

</div></body></html>