<html><body><div><div class="post-text" itemprop="text">

<p>I've got the following code:</p>

<pre><code>public static String getVersion() 
{
    PythonInterpreter interpreter = new PythonInterpreter();

    try 
    {
        interpreter.exec(IOUtils.toString(new FileReader("./Application Documents/Scripts/Version.py")));
        PyObject get_version = interpreter.get("get_latest_version");
        PyObject result = get_version.__call__(interpreter.get("url"));
        String latestVersion = (String) result.__tojava__(String.class);
        interpreter.close();
        return latestVersion;
    } catch (IOException ex) {
        ex.printStackTrace();
        interpreter.close();
        return Version.getLatestVersionOnSystem();
    }
</code></pre>

<p>For the sake of completeness, I'm adding the Python code:</p>

<pre><code>import urllib2 as urllib
import warnings

url = 'arcticlights.ca/api/paint&amp;requests?=version'

def get_latest_version(link=url):
    request = urllib.Request(link)
    handler = urllib.urllopen(request)
    if handler.code is not 200:
        warnings.warn('Invalid Status Code', RuntimeWarning)
    return handler.read()

version = get_latest_version()
</code></pre>

<p>It works flawlessly, but only 10% of the time. If I run it with a main like follows:</p>

<pre><code>public static void main(String[] args)
{
    for (int i = 0; i &lt; 10; i++) {
        System.out.println(getVersion());
    }   
}
</code></pre>

<p>It works the first time. It gives me the output that I want, which is the data from the http request that is written in my <code>Versions.py</code> file, which the java code above calls. After the second time, it throws this massive error (which is 950 lines long, but of course, I won't torture you guys). Here's the gist of it:</p>

<pre><code>Aug 26, 2015 10:41:21 PM org.python.netty.util.concurrent.DefaultPromise execute
SEVERE: Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
</code></pre>

<p>My Python traceback that is supplied at the end of the 950 line Java stack trace is mostly this:</p>

<pre><code>File "&lt;string&gt;", line 18, in get_latest_version 
urllib2.URLError: &lt;urlopen error [Errno -1] Unmapped exception: java.util.concurrent.RejectedExecutionException: event executor terminated&gt;
</code></pre>

<p>If anyone is curious, the seemingly offending line in my <code>get_latest_version</code> is just:</p>

<pre><code>handler = urllib2.urlopen(request)
</code></pre>

<p>Since the server that the code is calling is being run (by cherrypy) on the localhost on my network, I can see how it is interacting with my server. It actually sends two requests (and throws the exception right after the second).</p>

<pre><code>127.0.0.1 - - [26/Aug/2015:22:41:21] "GET / HTTP/1.1" 200 3 "" "Python-urllib/2.7"
127.0.0.1 - - [26/Aug/2015:22:41:21] "GET / HTTP/1.1" 200 3 "" "Python-urllib/2.7"
</code></pre>

<p>While I'm never going to run this code in a loop likely, I'm quite curious as to two things:</p>

<ul>
<li>Is the offending code my Python or Java code? Or could it just be an issue with Jython altogether?</li>
<li>What does the exception mean (it looks like a java exception)? Why is it being thrown when it is? Is there a way to make a loop like this work? Could this be written better?</li>
</ul>
    </div>
    </div></body></html>